# Generated by Django 3.2.3 on 2021-05-21 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siterysin', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Publication',
        ),
    ]
