# Generated by Django 3.2.3 on 2021-05-21 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siterysin', '0002_rename_post_publication'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, default=None, null=True, upload_to='')),
                ('description', models.CharField(blank=True, default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=50)),
                ('photos', models.ManyToManyField(to='siterysin.Photo')),
            ],
        ),
    ]
