# Generated by Django 3.2.3 on 2021-05-21 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siterysin', '0003_album_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='photo_title',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=''),
        ),
    ]
