# Generated by Django 3.2.3 on 2021-05-22 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siterysin', '0004_album_photo_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedBack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(default='noname', max_length=200)),
                ('email', models.EmailField(default='nomail', max_length=254)),
                ('text', models.TextField(default='')),
                ('title', models.CharField(default='', max_length=200)),
            ],
        ),
    ]
