# Generated by Django 3.2.3 on 2021-05-22 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siterysin', '0005_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='notitle', max_length=100)),
                ('file', models.FileField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='CategoryFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='notitle', max_length=100)),
                ('files', models.ManyToManyField(to='siterysin.File')),
            ],
        ),
    ]
