# Generated by Django 3.2.3 on 2021-05-22 17:04

from django.db import migrations, models
import siterysin.models


class Migration(migrations.Migration):

    dependencies = [
        ('siterysin', '0006_categoryfiles_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='photo_title',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=siterysin.models.file_path),
        ),
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=siterysin.models.file_path),
        ),
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=siterysin.models.file_path),
        ),
        migrations.AlterField(
            model_name='publication',
            name='photo',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=siterysin.models.file_path),
        ),
    ]
